# Generated by Django 4.2.2 on 2023-07-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_comentario_usuario_resposta_comentario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='foto',
            field=models.ImageField(default='logo.png', upload_to='blog/'),
        ),
    ]
