# Generated by Django 4.2.2 on 2023-07-06 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0005_alter_comentario_usuario_alter_resposta_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='comentario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='django_app.comentario'),
        ),
    ]
